spring:
  # ===============================
  # = DATASOURCE (for Development)
  # ===============================
  datasource:
    url: jdbc:mysql://localhost:3306/nkraft_db?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=Asia/Tokyo
    username: nkraft
    password: pass
    driver-class-name: com.mysql.cj.jdbc.Driver

  # ===============================
  # = JPA & Flyway
  # ===============================
  jpa:
    hibernate:
      # Flywayでスキーマを管理し、起動時にEntityとの整合性を検証します。
      ddl-auto: validate